# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-10 03:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Journal', '0002_entry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='picture',
        ),
        migrations.AddField(
            model_name='entry',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to=b''),
        ),
    ]
